### ISSUE TITLE
Add a page for closed problems

### ISSUE THREAD

**Issue by TarasBardiuk** [Kotany-IF070-WebUI-RoR/NewVasjuky#114]
PR https://github.com/Kotany-IF070-WebUI-RoR/NewVasjuky/pull/119

**Comment by TarasBardiuk** [comment]
@igorkasyanchuk, @Kmalynss, little question.
Link /issues (named "ЗВЕРНЕНЬ НАДІСЛАНО" on the root page) must lead to a page with all approved issues (open and closed) or only actual (not closed) issues?
At this moment we have "ЗВЕРНЕНЬ НАДІСЛАНО" for actual issues only, and if some issue from that list will be closed, it will be moved to "ПРОБЛЕМ ВИРІШЕНО".
Logically, we need to show all approved issues or just rename the link:)

**Comment by igorkasyanchuk** [comment]
you can new action

/issues/resolved to show all resolved issues.

and similar for others if needed
