### ISSUE TITLE
make some mockups to discuss the structure

### ISSUE THREAD

**Issue by arsenlol** [Kotany-IF070-WebUI-RoR/NewVasjuky#12]

**Comment by simplews** [comment]
@mis6ko13 , закинь може сюди лінк на мокапи?

**Comment by mis6ko13** [comment]
Here's a link for shared folder with mockups and some basic description inside:
https://drive.google.com/drive/folders/0B8agnsttnjnaLXF5amZWdmlvUFk?usp=sharing
I'm still working on them and soon there would be some changes...
Maybe it would be better to add them to the repo?

**Comment by simplews** [comment]
I don't think so, because we have images here, not code

**Comment by simplews** [comment]
Could we close this issue?

**Comment by denys281** [comment]
@simplews  please move link and any other information to wiki: https://github.com/Kotany-IF070-WebUI-RoR/NewVasjuky/wiki .

**Comment by simplews** [comment]
Done
