### ISSUE TITLE
creating header

### ISSUE THREAD

**Issue by f1nwe** [Kotany-IF070-WebUI-RoR/NewVasjuky#26]

**Comment by igorkasyanchuk** [comment]
better work on https://bootstrapious.com/p/universal-business-e-commerce-template

integrate this template. work with developer who was working on "basic bootstrap theme" and do it together

We need to have http://prnt.sc/dogitx something like this

home#index only one page what we need for now 

so you need to put JS/CSS/images to app folder (appropriarte in rails app)
change layout
implement home#index
add link to admin pages in header
