### ISSUE TITLE
Investigate existing services.

### ISSUE THREAD

**Issue by f1nwe** [Kotany-IF070-WebUI-RoR/NewVasjuky#5]
What kind of issues can be submitted.
How an issue can be submitted.
How do they track issue progress.

**Comment by f1nwe** [comment]
Some existing services
1. http://www.emvk.if.ua/ezvern
2. https://play.google.com/store/apps/details?id=ua.ivfr.mvk.mFrankivsk
3. http://opencity.in.ua
4. http://map.vmr.gov.ua

**Comment by f1nwe** [comment]
Services 1&2 are the official services developed by Ivano-Frankivsk local authorities. Users can submit issues with provided form by topics: Соціальний захист, Охорона здоров'я, Освіта, Культура, Спорт, Комунальне господарство, Транспорт і зв'язок, Утримання будинків, тарифи, Благоустрій міста, Реклама, Паркування, Служба оперативного реагування 15-80, Капітальне будівництво, Житлові питання, Архітектура та містобудування, Земельні питання, Торгівля, Забезпечення законності та правопорядку, Фінансові питання, Звернення до депутатів міської ради, Інші питання.
Users can submit text with attached up to 3 files. Permitted extensions of files aren't described on the page.
After the issue was submitted, user receives a unique code to track issue. This code shown on web page and also sends by e-mail. To track issue user have to go to http://www.emvk.if.ua/stan and fill in the code and solve easy arithmetical problem.

**Comment by f1nwe** [comment]
Service 3 was developed by NGO Open city association. It makes possible to report issues from several cities. City can be chosen at first step.
User can report issues to section "Problems and Solutions". Form contains fields "What would do you like to report", "Select location". Also it's possible to point place on map. Second part of form is different for each category. Service Open city allows to attach photo and video files.
Tracking is possible in Comments section of each reported and approved issue.

**Comment by f1nwe** [comment]
Service 4 is the official service developed by Vinnytsia local authorities.
Issues can be submitted by clicking on map and after that "Залишити звернення".
It opens a modal window with fields Контактна особа, Адреса, e-mail, Телефон, Тип питання. Reporter can select categories Аварійна ситуація, Енергетика, Транспорт, Зв’язок, Житлове господарство, Комунальне господарство, Благоустрій, Архітектура та містобудування, Торгівля, громадське харчування, Соціальна сфера, Охорона здоров’я, Освіта та культура, Інші питання, Повідомлення про помилку на мапі. Also reporter can attach file to form.
Page displays last 500 issues with additional fields "Звіт по виконанню" and "Пов’язани звернення". This fields allows to track progress on issue.

**Comment by denys281** [comment]
@Kmalynss  could we close this issue? :)

**Comment by denys281** [comment]
@f1nwe  Please, create wiki page with this information. https://github.com/Kotany-IF070-WebUI-RoR/NewVasjuky/wiki
